name: flutter_hive_example
description: A demonstration of using the hive package to store data locally with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0
  path_provider: ^1.5.1
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  hive_generator: ^0.7.0


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
